### ISSUE TITLE
1.19.3 | CTD on Loading New World

### ISSUE THREAD

**Issue by Dragonfly-Totem** [shaksternano/WMITAF#7]
Minecraft 1.19.3
Fabric Loader 0.14.14
Fabric API 0.74.0
bad packets 0.3.4
WTHIT 6.1.4
WMITAF Fabric 3.1.1

**Error Info**
[Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchFieldError: field_11142
	at io.github.shaksternano.wmitaf.client.util.fabric.ModNameUtil.hasId(ModNameUtil.java:196) ~[wmitaf-fabric-mc1.19-3.1.1.jar:?]
	at io.github.shaksternano.wmitaf.client.util.fabric.ModNameUtil.hasStatusEffects(ModNameUtil.java:185) ~[wmitaf-fabric-mc1.19-3.1.1.jar:?]
	at io.github.shaksternano.wmitaf.client.util.fabric.ModNameUtil.modNameNeedsToBeChanged(ModNameUtil.java:80) ~[wmitaf-fabric-mc1.19-3.1.1.jar:?]
	at io.github.shaksternano.wmitaf.client.util.fabric.ModNameUtil.getActualModName(ModNameUtil.java:48) ~[wmitaf-fabric-mc1.19-3.1.1.jar:?]
	at io.github.shaksternano.wmitaf.client.plugin.wthit.fabric.WthitItemModNameProvider.getHoveredItemModName(WthitItemModNameProvider.java:49) ~[wmitaf-fabric-mc1.19-3.1.1.jar:?]
	at mcp.mobius.waila.WailaClient.onItemTooltip(WailaClient.java:93) ~[wthit-fabric-6.1.4.jar:?]
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$1(FabricWailaClient.java:23) ~[wthit-fabric-6.1.4.jar:?]
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:34) ~[fabric-item-api-v1-2.1.10+312c329485-d3a356ccac261db4.jar:?]
	at net.minecraft.class_1799.handler$bhi000$getTooltip(class_1799.java:5655) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:828) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1591(class_310.java:829) ~[client-intermediary.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
	at java.util.Collections$2.forEachRemaining(Collections.java:4861) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_7454.method_43796(class_7454.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_1126.method_4799(class_1126.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_1124$class_7457.method_43807(class_1124.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_1124.method_43804(class_1124.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_43759(class_310.java:2636) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11106(class_634.java:1373) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11997(class_2788.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2788.method_11054(class_2788.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1144) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]

**Comment by shaksternano** [comment]
Fixed in the latest version.
